apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-heartbeat-egress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: pipeline-heartbeat
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: cribl-stream-standalone
      ports:
        - port: 9000
          protocol: TCP
