apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-heartbeat-edge-egress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: heartbeat-edge
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: cribl-edge-standalone
      ports:
        - port: 9420
          protocol: TCP
    - ports:
        - port: 443
          protocol: TCP
