[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.14"
extraPaths = ["tests"]

[tool.pytest.ini_options]
pythonpath = ["tests"]

[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
