---
# Allow Cribl Stream Standalone to receive data from OTEL collector and Edge Standalone.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-stream-ingress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: cribl-stream-standalone
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: otel-collector
      ports:
        - port: 4317  # OTLP gRPC from OTEL
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app: cribl-edge-standalone
      ports:
        - port: 8088  # HEC from Edge Standalone
          protocol: TCP
