---
# Allow OTEL collector to receive OTLP telemetry from any source.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-otel-ingress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: otel-collector
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 4317  # OTLP gRPC
          protocol: TCP
        - port: 4318  # OTLP HTTP
          protocol: TCP
