---
# Allow Cribl Edge Standalone to forward events to Cribl Stream Standalone.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-edge-standalone-egress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: cribl-edge-standalone
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: cribl-stream-standalone
      ports:
        - port: 10080  # Cribl HTTP input
          protocol: TCP
