apiVersion: v1
kind: Service
metadata:
  name: cribl-edge-standalone
  namespace: monitoring
  labels:
    app: cribl-edge-standalone
spec:
  type: ClusterIP
  selector:
    app: cribl-edge-standalone
  ports:
    - name: otel
      port: 9420
      targetPort: 9420
      protocol: TCP
    - name: ui
      port: 9000
      targetPort: 9000
      protocol: TCP
