apiVersion: v1
kind: Service
metadata:
  name: cribl-edge-standalone-ui
  namespace: monitoring
  labels:
    app: cribl-edge-standalone
spec:
  type: NodePort
  selector:
    app: cribl-edge-standalone
  ports:
    - name: ui
      port: 9000
      targetPort: 9000
      nodePort: 30910
      protocol: TCP
