apiVersion: v1
kind: Service
metadata:
  name: cribl-stream-managed
  namespace: monitoring
  labels:
    app: cribl-stream-managed
spec:
  type: ClusterIP
  selector:
    app: cribl-stream-managed
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: inputs
      port: 10080
      targetPort: 10080
      protocol: TCP
