apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cribl-stream-standalone
  namespace: monitoring
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: cribl-stream-standalone
