apiVersion: v1
kind: Service
metadata:
  name: cribl-stream-standalone
  namespace: monitoring
  labels:
    app: cribl-stream-standalone
spec:
  type: ClusterIP
  selector:
    app: cribl-stream-standalone
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: inputs
      port: 10080
      targetPort: 10080
      protocol: TCP
    - name: leader
      port: 4200
      targetPort: 4200
      protocol: TCP
